apiVersion: v1
kind: Service
metadata:
  name: resumeforge-api
  namespace: resumeforge
  labels:
    app.kubernetes.io/name: resumeforge-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: resumeforge
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: resumeforge-api

  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP