apiVersion: v1
kind: Service
metadata:
  name: resumeforge-web
  namespace: resumeforge
  labels:
    app.kubernetes.io/name: resumeforge-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: resumeforge
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: resumeforge-web

  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP